print("------ARTIFICIAL INTELLIGENCE(AI)--------")
print("AI allows computers and machines to perform tasks which")
print("normally requires human intelligence. They can make decisions,")
print("understand information, solve problems and interact with people.")
print("REAL WORLD EXAMPLES OF AI: ")
print("1. Smart Traffic Systems")
print("2. Game AI")
print("3. Virtual Assistants")

print("\n------MACHINE LEARNING (ML)--------")
print("ML is a branch of AI in which computers learn patterns from")
print("data and use these patterns to make predictions or decisions.")
print("We provide data so that system can learn from it instead of")
print("giving computer instructions for every situation.")
print("REAL WORLD EXAMPLES OF ML: ")
print("1. Recommendation Systems")
print("2. House Price Prediction Systems")
print("3. Spam Email Detection")

print("\n------DEEP LEARNING (DL)--------")
print("DL is a branch of ML that uses artficial neural networks with")
print("multiple layers. They can learn complex patterns from large amounts")
print("of data with less need for manually designing features.")
print("REAL WORLD EXAMPLES OF DL: ")
print("1. Medical Image Analysis")
print("2. Object Detection")
print("3. Face Recognition")

print("\n--------------------------------------------------------------------")
print("WHY IS DL USEFUL FOR COMPUTER VISION?")
print("DL is very useful for computer vision because image contain")
print("large amount of complex information. Traditional methods often")
print("require humans to manually design features such as edges, shapes")
print("and textures. DL models especially CNN (Convolutional Neural Networks)")
print("can automatically learn useful features from images. In early years")
print("network can learn simple features such as edges and textures. In deeper layers")
print("it can learn more complex features such as shapes, objects")
print("and patterns. That's why it is useful for many computer vision applications")
print("Such as: ")
print("1. Medical Image Analysis")
print("2. Object Detection")
print("3. Face Recognition")
print("4. Image Classification")
print("5. Self Driving Vehicle Vision Systems")
